//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageMastery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT_REQUEST
    {
        public int req_Id { get; set; }
        public string req_Email { get; set; }
        public string req_Contact { get; set; }
        public string req_Message { get; set; }
        public string req_Location { get; set; }
    }
}
