//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageMastery.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LanguageMasteryEntities : DbContext
    {
        public LanguageMasteryEntities()
            : base("name=LanguageMasteryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMIN> ADMINs { get; set; }
        public virtual DbSet<CONTACT_REQUEST> CONTACT_REQUEST { get; set; }
        public virtual DbSet<COURSE> COURSEs { get; set; }
        public virtual DbSet<ENROLMENT> ENROLMENTs { get; set; }
        public virtual DbSet<RATING> RATINGs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STUDENT> STUDENTs { get; set; }
    }
}
