//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageMastery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RATING
    {
        public int rat_Id { get; set; }
        public Nullable<int> rat_Star { get; set; }
        public Nullable<System.DateTime> rat_Date { get; set; }
        public string rat_Comment { get; set; }
        public Nullable<int> STU_ID { get; set; }
        public Nullable<int> CR_ID { get; set; }
    
        public virtual COURSE COURSE { get; set; }
        public virtual STUDENT STUDENT { get; set; }
    }
}
